### PR TITLE
[Admin] Backend view - duplicate search result on filtered list 

### LINKED ISSUE #275: [Bug]: [Admin] Backend view - duplicate search result on filtered list
### Expected behavior

In the customers filter section in the [admin] backend view, if we search for the customers using the search criterias mentioned below (Steps to reproduce) , then the same customer/entry should be displayed only once.

### Actual behavior

image

Note: In the customers filter section in the [admin] backend view, duplicate results are displayed. If we search for the customers uusing the search criterias mentioned below (Steps to reproduce) , then the same customer/entry is displayed more than once.

### Steps to reproduce

Search criterias/filters

1. "Customers" - match any
2. "Segments" - match any
3. Input the customer-field "email"
4. Input more than one segment-field
5.  "Apply filters"

### PR DESCRIPTION
**Pull request by aryaantony92**
Resolves #275

### CODE REVIEW

File: src/CustomerList/SearchHelper.php [hunk 1]
```diff
@@ -138,6 +138,7 @@ public function addListingFilters(Concrete $listing, array $filters, User $admin
                         $segments[] = $segment;
                     }
                 }
+                $handler->getListing()->setGroupBy('o_id', true);
```
Comment (dvesh3) [inline src/CustomerList/SearchHelper.php]: How about we set groupBy in `CustomerController:buildListing()`? as this will also used by export/download.

Comment (dvesh3) [reply src/CustomerList/SearchHelper.php]: @aryaantony92 please see
