### PR TITLE
Fixed autosave not preserving versions issue

### LINKED ISSUE #300: [Bug]: Pimcore X autoSave fully saves customer DataObject
### Expected behavior

Pimcore X _autoSave_ request only saves version of customer DataObject with updated subset of segments

### Actual behavior

Pimcore X _autoSave_ request updates segment list and fully saves customer DataObject

### Steps to reproduce

**Reproduce**

1. Make sure to enable autoSave for DataObjects
2. Define DataObject with related segements
3. Setup SegmentBuilder, which updates segments based on data in customer DataObject
4. Change object field in customer DataObject (e.g. checkbox isActive, which adds a segment "active" to the customer DataObject
5. Wait for autoSave request to finish
6. Reload DataObject - The draft is now fully published

**Possible points of interest:** 

- PimcoreObjectEventListener: onPostUpdate (doesn't check if autoSave)
- DefaultCustomerSaveManager: postUpdate
- DefaultSegmentBuilderExecutor: buildCalculatedSegmentsOnCustomerSave / buildCalculatedSegments
- DefaultSegmentMerger: saveMergedSegments
- DefaultCustomerSaveManager: saveWithOptions (returns $customer->save() without further checks)

### PR DESCRIPTION
**Pull request by aashan10**
Resolves #300

### CODE REVIEW

**Review by dvesh3 — COMMENTED** [review]
The fix now creates a new version instead of publishing it but it still updates the latest published version.

e.g., changing gender on customer
1. Gender is "male" in published version
image
2. change gender value to "female"
image
3. Remove Draft:
image
4. Gender value was not reverted to "male"
image

File: src/Event/PimcoreObjectEventListener.php [hunk 1]
```diff
@@ -63,7 +63,10 @@ public function onPreUpdate(ElementEventInterface $e)
 
     public function onPostUpdate(ElementEventInterface $e)
     {
-        if (!$e instanceof DataObjectEvent) {
+        //do not update index when auto save or only saving version or when $e not DataObjectEvent
```
Comment (dvesh3) [inline src/Event/PimcoreObjectEventListener.php]: the comment is wrong

Comment (aashan10) [reply src/Event/PimcoreObjectEventListener.php]: Fixed it
